# Generated by Django 4.1.4 on 2022-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
